export class MagicAudio {
  constructor() {this.sound=true;this.volume=.22;this.nodes=new Set();this.lastScroll=-Infinity;this.buffers={};this.clipData={};this.audioRevision=0;}
  configure({sound=this.sound,volume=this.volume}={}) {this.sound=sound;this.volume=Math.max(0,Math.min(.5,volume));if(this.master)this.master.gain.value=this.volume;if(!sound)this.stop();}
  unlock() {try {if(!this.sound)return;if(!this.ctx){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;this.ctx=new Audio();this.master=this.ctx.createGain();this.master.gain.value=this.volume;this.master.connect(this.ctx.destination);this.setClips(this.clipData);}return this.ctx.resume().catch(()=>{});}catch{}}
  async setClips(clips={}) {this.clipData=clips;const revision=++this.audioRevision;this.buffers={};if(!this.ctx)return;for(const key of ['click','scroll','transform','remi','aiko','hazuki']){try {const data=clips[key]?.data;if(!data||data.length>1000000||!/^data:audio\/[\w.+-]+;base64,/.test(data))continue;const bytes=Uint8Array.from(atob(data.split(',')[1]),c=>c.charCodeAt(0));const buffer=await this.ctx.decodeAudioData(bytes.buffer);if(revision!==this.audioRevision)return;if(buffer.duration<=15)this.buffers[key]=buffer;}catch{}}}
  playClip(key,delay=0) {const buffer=this.buffers[key];if(!buffer||!this.sound||this.ctx?.state!=='running')return false;const source=this.ctx.createBufferSource();source.buffer=buffer;source.connect(this.master);source.start(this.ctx.currentTime+delay);this.nodes.add(source);source.onended=()=>{this.nodes.delete(source);source.disconnect();};return true;}
  duration(character) {return Math.max(3.8,Math.min(16.25,(this.buffers[character]?.duration||0)+1.25),Math.min(15,this.buffers.transform?.duration||0));}
  tone(frequency,delay=0,length=.65,gain=.25) {if(!this.sound||this.ctx?.state!=='running')return;const start=this.ctx.currentTime+delay;
    for(const [multiple,level] of [[1,1],[2,.2],[3,.055]]){const osc=this.ctx.createOscillator(),env=this.ctx.createGain();osc.type='sine';osc.frequency.value=frequency*multiple;env.gain.setValueAtTime(0,start);env.gain.linearRampToValueAtTime(gain*level,start+.008);env.gain.exponentialRampToValueAtTime(.0001,start+length);osc.connect(env);env.connect(this.master);osc.start(start);osc.stop(start+length+.02);this.nodes.add(osc);osc.onended=()=>{this.nodes.delete(osc);osc.disconnect();env.disconnect();};}}
  scroll(direction) {if(!this.sound||this.ctx?.state!=='running')return;const now=performance.now();if(now-this.lastScroll<Math.max(140,(this.buffers.scroll?.duration||0)*1000))return;this.lastScroll=now;if(this.playClip('scroll'))return;const notes=direction>0?[1046.5,1318.5,1568]:[1568,1318.5,1046.5];notes.forEach((f,i)=>this.tone(f,i*.045,.38,.15));}
  transform(character='remi') {this.playClip(character,1.2);if(this.playClip('transform'))return;[523.25,659.25,783.99,1046.5,987.77,1174.66,1318.5,1568,1318.5,1760,2093].forEach((f,i)=>this.tone(f,i*.245,.9,.21));[523.25,659.25,783.99].forEach(f=>this.tone(f,2.95,1.2,.12));}
  capture() {[1046.5,1318.5,2093].forEach((f,i)=>this.tone(f,i*.08,.75,.18));}
  click() {if(this.playClip('click'))return;[1318.5,1760,2093].forEach((f,i)=>this.tone(f,i*.055,.45,.16));}
  stop() {for(const n of this.nodes){try{n.stop();}catch{}}this.nodes.clear();}
  dispose() {this.stop();this.ctx?.close().catch(()=>{});}
}
